config/routes.rb
Openmedia::Application.routes.draw do

  devise_for :admins

  match '/admin' => 'admin/home#index', :as => :admin_root
  match '/about' => 'admin/home#about', :as => :about
  match '/support' => 'admin/home#support', :as => :support

  root :to => "public/welcome#index"
  
  scope :module => 'public' do
    resources :sites do
      collection do
        get :autocomplete_geoname
      end
    end
    resources :collections
    resources :classes
    resources :maps
    resources :dashboards
    resources :welcome do
      collection do
        get :license
      end
    end
  end
  
  namespace :admin do
    resources :csvs do
      collection do
        get :import
        post :upload
      end
    end
    resource :site
    resource :community
    resources :contacts do
      collection do
        get :new_email
        get :new_telephone
        get :new_address
      end
      member do
        get :show_contact
      end
    end
    resources :dashboards do
      collection do
        get :new_group
        get :new_measure
      end
    end
    resources :maps
    
    namespace :linked_data do
      resources :collections do
        resources :vocabularies do
          resources :types
          resources :properties
        end
      end
    end

    namespace :schema do
      resources :collections do
        resources :classes
      end
      resources :classes do
        collection do
          get :new_property
          get :autocomplete
          get :property_list
        end
      end
    end    
    
    resources :datasources do
      collection do
        get :new_property
      end

      member do
        get :raw_records
        get :publishing
        put :publish
      end
    end
    
    resources :catalogs
    resources :properties
    resources :settings
    resources :reports
    resources :vcards
    resources :schedules
    resources :data_types
  end

end

app/models/linked_data/basic.rb
class LinkedData::Basic < CouchRest::Model::Base
  property :serial_number
  property :data_source_id
  timestamps!

  design do
    view :by_serial_number
    view :by_data_source_id
  end

end

app/models/linked_data/collection.rb
require 'rdf/couchdb'
class LinkedData::Collection < CouchRest::Model::Base

  use_database VOCABULARIES_DATABASE
  unique_id :identifier
  
  property :identifier, String
  property :term, String        # Escaped vocabulary name suitable for inclusion in IRI
  property :label, String       # User assigned name, RDFS#Label
  property :comment, String     # RDFS#Comment
  property :tags, [String]
  property :hidden, TrueClass, :default => false
  
  # property :namespace, LinkedData::Namespace
  property :base_uri, String
  property :authority, String
  property :uri, String

  timestamps!
  
  validates_presence_of :term
  validates_presence_of :base_uri
  validates_presence_of :authority
  validates_uniqueness_of :identifier, :view => 'all'

  ## Callbacks
  before_create :generate_uri
  before_create :generate_identifier
  
  def namespace=(ns={})
    self.base_uri = ns.base_uri unless ns.base_uri.nil?
    self.authority = ns.authority unless ns.authority.nil?
  end
  
  def namespace
    Hash[:base_uri => self.base_uri, :authority => self.authority]
  end

  design do
    view :by_label
    view :by_term
    view :by_uri
    view :by_base_uri
    view :by_authority
    
    # view :by_base_uri,
    #   :map =>
    #     "function(doc) {
    #       if (doc['type'] == 'LinkedData::Collection' && doc['namespace']['base_uri']) {
    #         emit(doc['namespace']['base_uri']);
    #         }
    #       }"
    # 
    # view :by_authority,
    # :map =>
    #   "function(doc) {
    #     if (doc['type'] == 'LinkedData::Collection' && doc['namespace']['authority']) {
    #       emit(doc['namespace']['authority']);
    #       }
    #     }"
    
    view :tag_list,
      :map =>
        "function(doc) {
          if (doc['model'] == 'LinkedData::Collection' && doc.tags) {
            doc.tags.forEach(function(tag) {
              emit(tag, 1); 
              });
            }
          }"
  end
  
  ## Return a Hash with URI's as keys and Collection hashes in an associated Array
  ## Calling with an empty URI will return all Collections
  def self.sort_by_base_uri(uri = '')
    @sorted_collections = Hash.new
    if uri.empty?
      all_collections = LinkedData::Collection.all
    else
      all_collections = LinkedData::Collection.by_base_uri(:key => uri)
    end
    
    all_collections.each do |c| 
      @sorted_collections.key?(c.base_uri) ? @sorted_collections[c.base_uri] << c : @sorted_collections[c.base_uri] = Array.[](c)
    end
    @sorted_collections
  end

private
  def generate_uri
    self.label ||= self.term
    rdf_uri = RDF::URI.new(self.base_uri)/"collections#"/escape_string(self.term)
    self.uri = rdf_uri.to_s
  end

  def generate_identifier
    self['identifier'] = self.class.to_s.split("::").last.downcase + '_' +
                         self.authority + '_' + 
                         escape_string(self.term.downcase) if new?
  end
  
  def escape_string(str)
    str.gsub(/[^A-Za-z0-9]/,'_').squeeze('_')
  end
  
end

app/models/linked_data/db_parser.rb
class LinkedData::DbParser < LinkedData::Parser
  
  # ch = ActiveRecord::ConnectionAdapters::ConnectionHandler.new
  # db = ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.new
  # db = ActiveRecord::ConnectionAdapters::MysqlAdapter.new
  
  
end

app/models/linked_data/metadata.rb
class LinkedData::Metadata < Hash
  include CouchRest::Model::Embeddable
  
  # property :creator
  # property :publisher 
  # property :title 
  property :language, :default => 'en-US'
  property :conforms_to 
  property :description
  property :resourcetype, :default => "RDF::DCTYPE.Dataset"

end

app/models/linked_data/namespace.rb
class LinkedData::Namespace

  attr_reader :base_uri, :authority, :domain, :subdomain

  def initialize(openmedia_url)
    parts = openmedia_url.to_s.split('.')
    @subdomain = parts.first.split("http://").last
    @domain = openmedia_url.to_s.split(subdomain + '.').last

    # authority => "civicopenmedia_us_dcgov"
    @authority = domain.gsub('.','_') + '_' + subdomain
    @base_uri = "http://#{@domain}/#{@subdomain}"
    Hash[:base_uri => @base_uri, :authority => @authority, :domain => @domain, :subdomain => @subdomain]
  end

end

app/models/linked_data/property.rb
class LinkedData::Property
  include CouchRest::Model::Embeddable
  
  property :term, String                              # Escaped vocabulary name suitable for inclusion in IRI
  property :alias, String                             # Alternate term
  property :label, String                             # RDFS#Label
  property :expected_type, String                     # URI for data type
  property :format, String                            # Output format styling
  property :key, TrueClass, :default => false         # Create index on this property?
  property :comment, String                           # RDFS#Comment
  property :deprecated, TrueClass, :default => false  # Deprecated properties may not be used 
                                                       # for future vocabularies            
  def term=(val)
    write_attribute('term', val)
    write_attribute('label', val) if read_attribute('label').nil?
  end
  
  def deprecated?
    self.deprecated
  end

end

app/models/linked_data/raw_record.rb
class LinkedData::RawRecord < CouchRest::Model::Base
 
  use_database STAGING_DATABASE
  
  belongs_to :data_source, :class_name => 'LinkedData::DataSource'

  property :serial_number, String
  property :published, Time
  timestamps!


  design do
    view :by_serial_number
    view :by_data_source_id

  #   # view :by_data_resource_id_and_published
    view :by_unpublished, 
            :map =>"function(doc) {
                      if (doc['model']=='LinkedData::RawRecord' && doc['published']==null) {
                        emit(doc.data_source_id, 1);
                      }
                    }"
  end
  
  def published?
    self.published
  end
  
end

app/controllers/admin/linked_data/collections_controller.rb
class Admin::LinkedData::CollectionsController < Admin::BaseController

    before_filter :convert_hidden, :only=>[:update, :create]

    def index
      ns = ::LinkedData::Namespace.new current_site.url
      @collections = ::LinkedData::Collection.by_base_uri(:key => ns.base_uri)
    end

    def new
      @collection = ::LinkedData::Collection.new
    end

    def create
      @new_collection = params[:collection]
      @new_collection["tags"] = @new_collection["tags"].split(',')
      @new_collection["base_uri"] = current_site.url
      @collection = ::LinkedData::Collection.new(@new_collection)
      
      if @collection.save
        flash[:notice] = 'Collection successfully created.'
        redirect_to admin_om_linked_data_collection_path(@collection)
      else
       flash[:error] = 'Unable to create Collection.'
       render :action => "new"
      end
    end

    def show
      @collection = ::LinkedData::Collection.find(params[:id])
      @sorted_vocabs = ::LinkedData::Vocabulary.sort_by_authority
      
      site_ns = ::LinkedData::Namespace.new current_site.url
      om_ns = ::LinkedData::Namespace.new om_site.url
      
      @site_vocabs = @sorted_vocabs.delete(site_ns.authority) { |val| val = [] }
      @commons_vocabs = @sorted_vocabs.delete(om_ns.authority) { |val| val = [] }
      @other_vocabs = @sorted_vocabs
    end

    def edit
      @collection = ::LinkedData::Collection.find(params[:id])
      @collection["tags"] = @collection["tags"].join(',')
    end

    def update
      @collection = ::LinkedData::Collection.find(params[:id])
      @update_collection = params[:collection]
      @update_collection["tags"] = @update_collection["tags"].split(',')
      @collection.attributes = @update_collection
      
      if @collection.save
        flash[:notice] = 'Collection successfully updated.'
        redirect_to admin_om_linked_data_collection_path(@collection)
#        redirect_to admin_om_linked_data_collection_path(rdf_id(@collection.uri))
      else
       flash[:error] = 'Unable to update Collection.'
       render :action => "edit"
#        redirect_to edit_admin_om_linked_data_collection_path(@collection.id)
      end
    end

    def destroy
      @collection = ::LinkedData::Collection.find(params[:id])

      # TODO - Deleting collection will require support for deleting Vocabs and Properties
      
      flash[:notice] = 'Unable to delete Collection.'
      redirect_to admin_om_linked_data_collections_path
    end

private
  def convert_hidden
    params[:collection][:hidden] = (params[:collection][:hidden] && params[:collection][:hidden] == '1') ? true : false
  end


  end

app/controllers/admin/linked_data/vocabularies_controller.rb
class Admin::LinkedData::VocabulariesController < Admin::BaseController

  def autocomplete
    # startkey = params[:term].downcase.gsub(/[^a-z0-9]/,'_').gsub(/^\-|\-$/,'')
    # @uris = OpenMediaLinkedData::RDFS::Class.prefix_search(startkey)
    # render :json=>@uris.collect{|u| {:id=>u.to_s, :label=>u.to_s, :value=>(u.fragment || u.path.split('/').last)} }    
  end

  def index
    @vocabularies = LinkedData::Vocabulary.all
  end

  def new
    @collection = LinkedData::Collection.get(params[:collection_id])
    @vocabulary = LinkedData::Vocabulary.new
  end

  def new_property
    @property = LinkedData::Property.new
    render :partial=>'property', :locals=>{:base_name=>'class[properties][]', :property=>@property}, :layout=>nil
  end

  def show
    @collection = LinkedData::Collection.get(params[:collection_id])
    @vocabulary = LinkedData::Vocabulary.get(params[:id])
  end

  def create
    @collection = LinkedData::Collection.get(params[:collection_id])
    
    @new_vocabulary = params[:vocabulary]
    @new_vocabulary["tags"] = @new_vocabulary["tags"].split(',')
    @new_vocabulary["base_uri"] = current_site.url
    @new_vocabulary["collection"] = @collection
    @vocabulary = LinkedData::Vocabulary.new(@new_vocabulary)
    
    if @vocabulary.save
      flash[:notice] = 'Vocabulary successfully created.'
      redirect_to admin_om_linked_data_collection_vocabulary_path(@collection, @vocabulary)
    else
     flash[:error] = 'Unable to create Vocabulary.'
     render :action => "new"
    end
  end
  
  def edit
    @collection = LinkedData::Collection.get(params[:collection_id])
    @vocabulary = LinkedData::Vocabulary.get(params[:id])
    @vocabulary["tags"] = @vocabulary["tags"].join(',')
  end

  def update
    @collection = LinkedData::Collection.get(params[:collection_id])
    @vocabulary = LinkedData::Vocabulary.find(params[:id])
    @update_vocabulary = params[:vocabulary]
    @update_vocabulary["tags"] = @update_vocabulary["tags"].split(',')
    @vocabulary.attributes = @update_vocabulary

    if @vocabulary.save
      flash[:notice] = 'Vocabulary successfully updated.'
      redirect_to admin_om_linked_data_collection_vocabulary_path(@collection, @vocabulary)
    else
     flash[:error] = 'Unable to update Vocabulary.'
     render :action => "edit"
    end
    
  end

  def destroy
  end

end

app/controllers/admin/om_linked_data/collections_controller.rb
class Admin::OmLinkedData::CollectionsController < Admin::BaseController

    before_filter :convert_hidden, :only=>[:update, :create]

    def index
      ns = ::OmLinkedData::Namespace.new current_site.url
      @collections = ::OmLinkedData::Collection.by_base_uri(:key => ns.base_uri)
    end

    def new
      @collection = ::OmLinkedData::Collection.new
    end

    def create
      @new_collection = params[:collection]
      @new_collection["tags"] = @new_collection["tags"].split(',')
      @new_collection["base_uri"] = current_site.url
      @collection = ::OmLinkedData::Collection.new(@new_collection)
      
      if @collection.save
        flash[:notice] = 'Collection successfully created.'
        redirect_to admin_om_linked_data_collection_path(@collection)
      else
       flash[:error] = 'Unable to create Collection.'
       render :action => "new"
      end
    end

    def show
      @collection = ::OmLinkedData::Collection.find(params[:id])
      @sorted_vocabs = ::OmLinkedData::Vocabulary.sort_by_authority
      
      site_ns = ::OmLinkedData::Namespace.new current_site.url
      om_ns = ::OmLinkedData::Namespace.new om_site.url
      
      @site_vocabs = @sorted_vocabs.delete(site_ns.authority) { |val| val = [] }
      @commons_vocabs = @sorted_vocabs.delete(om_ns.authority) { |val| val = [] }
      @other_vocabs = @sorted_vocabs
    end

    def edit
      @collection = ::OmLinkedData::Collection.find(params[:id])
      @collection["tags"] = @collection["tags"].join(',')
    end

    def update
      @collection = ::OmLinkedData::Collection.find(params[:id])
      @update_collection = params[:collection]
      @update_collection["tags"] = @update_collection["tags"].split(',')
      @collection.attributes = @update_collection
      
      if @collection.save
        flash[:notice] = 'Collection successfully updated.'
        redirect_to admin_om_linked_data_collection_path(@collection)
#        redirect_to admin_om_linked_data_collection_path(rdf_id(@collection.uri))
      else
       flash[:error] = 'Unable to update Collection.'
       render :action => "edit"
#        redirect_to edit_admin_om_linked_data_collection_path(@collection.id)
      end
    end

    def destroy
      @collection = ::OmLinkedData::Collection.find(params[:id])

      # TODO - Deleting collection will require support for deleting Vocabs and Properties
      
      flash[:notice] = 'Unable to delete Collection.'
      redirect_to admin_om_linked_data_collections_path
    end

private
  def convert_hidden
    params[:collection][:hidden] = (params[:collection][:hidden] && params[:collection][:hidden] == '1') ? true : false
  end


  end

app/controllers/admin/schema/collections_controller.rb
class Admin::Schema::CollectionsController < Admin::BaseController

  before_filter :load_collection
  before_filter :convert_hidden, :only=>[:update, :create]

  def index
    @collections = om_site.skos_collection.sub_collections.sort{|c1,c2| c1.label <=> c2.label}
    @collections.concat(current_site.skos_collection.sub_collections.sort{|c1,c2| c1.label <=> c2.label}) unless current_site = om_site
  end

  def new
    @collection = OpenMedia::Schema::SKOS::Collection.new
  end

  def show
    @collection = ::OmLinkedData::Collection.get(params[:id])
    
    @collection = OpenMedia::Schema::SKOS::Collection.for(params[:id])
    @classes = @collection.concepts.collect {|c| c.rdfs_class}.select{|c| current_site.skos_collection.uri.parent==c.uri.parent.parent}
  end

  def create
    @collection = OpenMedia::Schema::SKOS::Collection.create_in_collection!(current_site.skos_collection, params[:collection])
    if @collection.errors.count == 0
      flash[:notice] = 'Collection successfully created.'
      redirect_to admin_schema_collection_path(rdf_id(@collection.uri))
    else
      render 'new'
    end
  end

  def update
    @collection.update!(params[:collection].symbolize_keys)
    flash[:notice] = 'Collection successfully updated.'
    redirect_to admin_schema_collection_path(rdf_id(@collection.uri))
  end

  def destroy
    current_site.skos_collection.delete_member!(@collection.uri)
    @collection.destroy!    
    flash[:notice] = 'Collection successfully deleted.'
    redirect_to admin_schema_collections_path
  end
  
private
  def load_collection
    @collection = OpenMedia::Schema::SKOS::Collection.for(params[:id]) if params[:id]
  end

  def convert_hidden
    params[:collection][:hidden] = (params[:collection][:hidden] && params[:collection][:hidden] == '1') ? true : false
  end


end

app/views/admin/linked_data/collections/_form.html.erb
 <div class="grid_8">
		<div id="forms">
		<%= form_for :collection, 
		    :url => @collection.new? ? admin_linked_data_collections_path : admin_linked_data_collection_path(@collection), 
		    :html => {:method => @collection.new? ? :post : :put } do |f| %>
			<div class="form-errors"><%= f.error_messages %></div>
			<%#= f.hidden_field :namespace_id, :value => @collection['namespace_id'] if @collection['namespace_id'] %>
			<%#= f.hidden_field :identifier, :value => @collection['identifier'] if @collection['identifier'] %>
			<fieldset class="omega">
				<ol>
				  <li><%= f.label :label, :class => "standard" %> <%= f.text_field :label, :class => "standard" %></li>
				  <li><%= f.label :comment, 'Comment', :class => "standard" %> <%= f.text_area :comment, :rows => 5, :class => "wide" %></li>
				  <li><%= f.label :tags, 'Tags', :class => "standard" %> 
							<%= f.text_area :tags, {:rows => 3, :class => "wide", :prompt => 'Enter list of comma-separated terms'} %></li>
			    <fieldset>
			      <legend>Options</legend>
			      <ol>
							<li><%= f.check_box :hidden, {:class => 'checkbox'} %> <%= f.label :hidden, 'Hidden?' %></li>
			      </ol>
			    </fieldset>
				</ol>
			</fieldset>
			<fieldset class="submit omega">
				<ol>
					<li><%= f.submit "Save", :class => "submit"%> <%= link_to 'Back', :back %></li> 
				</ol>
			</fieldset>
		  <% end %>	
     </div>
</div>

<div class="grid_4">
	<div class="box articles">
		<div class="block" id="articles">
			<div class="first article">
				<h3><a href="#">Article Heading</a></h3>
				<h4>Subheading</h4>
				<p class="meta">Vancouver, BC — Wednesday, 23 April 2008</p>
				<p>Something here about role of Datasets in system</p>
			</div>
		</div>
	</div>
</div>

app/views/admin/linked_data/collections/edit.html.erb
<% title "Edit Collection" %>
<%= render :partial => 'form' %>

app/views/admin/linked_data/collections/index.html.erb
<% title "Collections" %>
<div class="grid_12">
  <%= link_to 'Add Collection', new_admin_linked_data_collection_path %>
	<hr />
</div>
<div class="grid_8">
	<div id="filter-collections" style="display:inline-block;">
		<input type="radio", id="radio1" name="radio" checked="checked" /><label for="radio1">Site</label>
		<input type="radio", id="radio2" name="radio"  /><label for="radio2">Commons</label>
		<input type="radio", id="radio3" name="radio"  /><label for="radio3">All</label>
	</div>
  <div class="block" id="tables">
    <table>
		<thead>
			<tr>
		    <th>Label</th>
		    <th>ID</th>
		    <th>No. Vocabularies</th>
		    <th>No. Records</th>
		  </tr>
		</thead>
		<% if @collections.nil? %>
			<tr><td colspan=4>No Collections found.</td></tr>
		<% else %>
			<% @collections.each do |c| %>
			<tr>
			  <td><%= link_to c.label, admin_linked_data_collection_path(c) %></td>
			  <td><%= c.identifier.split("collection_openmedia_dev_").last  %></td>
				<td><%= LinkedData::Vocabulary.find_by_collection_id(c.identifier).length %>
				<td>Use reduce to sum number of instances</td>
			</tr>
			<% end %>
		<% end %>
    </table>
  </div>
</div>

<div class="grid_4">
	<div class="box articles">
		<div class="block" id="articles">
			<div class="first article">
				<h3>Organize Data Content</h3>
				<p class="meta">Help others find and use your site's data.</p>
				<p>OpenMedia Collections and Vocabularies add uniformity to data content and group that content into common concepts.</p>
				<p>Here you will find defined Collections: common categories where you may publish uploaded content.</p>
				<p>Within Collections, Vocabularies for open and consensus standards are provided (as available) to make it easy to quickly publish and share information using common terms and vocabularies.</p>
				<p>When you upload new data sources, you may associate the content with existing Vocabulary or create a new one based on the new information</p>
				<p>If an appropriate Collection or Vocabulary isn't already available, you may also add your own.</p>
			</div>
		</div>
	</div>
</div>

app/views/admin/linked_data/collections/new.html.erb
<% title "Add Collection" %>
<%= render :partial => 'form' %>

app/views/admin/linked_data/collections/show.html.erb
<% title "Collection: #{@collection.label}" %>
<div class="grid_12" >
	<p class="page-nav">
		<%= link_to "All Collections", admin_linked_data_collections_path %> |
		<%= link_to "Edit", edit_admin_linked_data_collection_path(@collection) %> |
		<%= link_to 'Delete', admin_linked_data_collection_path(@collection), 
					:confirm => "Are you sure you want to delete this collection, all its Vocabularies, and all of the data those Vocabularies contain?", 
					:method => :delete %>
	</p>
	<hr />
</div>
<div class="grid_7">
	<div class="box">
		<h2><%= @collection.label %></h2>
		<div class="block">
			<% if @collection.comment.nil? %>
				<%= link_to "Add Comment", edit_admin_linked_data_collection_path(@collection) %>
			<% else %>
				<p><%= @collection.comment %></p>
				<p><%= link_to "Edit Description", edit_admin_linked_data_collection_path(@collection) %>
			<% end %>
			<% if @collection.tags.length > 0 %>
				<h5>Tags</h5>
				<ul>
					<% @collection.tags.sort.each do |t| %>
						<li><%= t %></li>
					<% end %>
				</ul>
			<% end %>
		</div>
	</div>
</div>
<div class="grid_5 omega">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Vocabularies</a></li>
			<li><a href="#tabs-2">Sites</a></li>
		</ul>
		<div id="tabs-1">
			<h5>Vocabularies used from the Commons</h5>
			<hr />
			<ul>
				<%= "<li>None listed</li>".html_safe if @commons_vocabs.length == 0 %>
				<% @commons_vocabs.each do |v| %>
					<li><%= link_to v.label, admin_linked_data_collection_vocabulary_path(@collection, v.identifier) %></li>
				<% end %>
			</ul>
			<h5>Vocabularies created for this Collection</h5>
			<hr />
			<ul>
				<%= "<li>None listed</li>".html_safe if @site_vocabs.length == 0 %>
				<% @site_vocabs.each do |v| %>
					<li><%= link_to v.label, admin_linked_data_collection_vocabulary_path(@collection, v) %> <%#= "(#{vocab.instance_count})" %></li>
				<% end %>
			</ul>
			<p><%= link_to "Add Vocabulary", new_admin_linked_data_collection_vocabulary_path(@collection), {:class => 'add-element'} %><p>
		</div>
		<div id="tabs-2">
			<p>Sites with data in this Collection</p>
			<hr />
			<ul>
				<li>None listed</li>
			</ul>
		</div>
	</div>
	
</div>