config/routes.rb
Openmedia::Application.routes.draw do

  devise_for :admins

  match '/admin' => 'admin/home#index', :as => :admin_root
  match '/about' => 'admin/home#about', :as => :about
  match '/support' => 'admin/home#support', :as => :support

  root :to => "public/welcome#index"
  
  scope :module => 'public' do
    resources :sites do
      collection do
        get :autocomplete_geoname
      end
    end
    resources :collections
    resources :classes
    resources :maps
    resources :dashboards
    resources :welcome do
      collection do
        get :license
      end
    end
  end
  
  namespace :admin do
    resources :csvs do
      collection do
        get :import
        post :upload
      end
    end
    resource :site
    resource :community
    resources :contacts do
      collection do
        get :new_email
        get :new_telephone
        get :new_address
      end
      member do
        get :show_contact
      end
    end
    resources :dashboards do
      collection do
        get :new_group
        get :new_measure
      end
    end
    resources :maps
    
    namespace :linked_data do
      resources :collections do
        resources :vocabularies do
          resources :types
          resources :properties
        end
      end
    end

    namespace :schema do
      resources :collections do
        resources :classes
      end
      resources :classes do
        collection do
          get :new_property
          get :autocomplete
          get :property_list
        end
      end
    end    
    
    resources :datasources do
      collection do
        get :new_property
      end

      member do
        get :raw_records
        get :publishing
        put :publish
      end
    end
    
    resources :catalogs
    resources :properties
    resources :settings
    resources :reports
    resources :vcards
    resources :schedules
    resources :data_types
  end

end

app/views/shared/_chart.html.erb
<% content_for :head do %>
	<%= javascript_include_tag 'http://www.google.com/jsapi', 'jquery.sparkline.js' %>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
	<div class="box">
  
  <p>
    <% if public %>
	    <span style="float: right">
	      Join the OpenMedia Community! <a href="<%= url_for(:action=>'new', :controller=>'public/sites', :host=>OM_DOMAIN) %>">Sign up</a>
	    </span>
    <% end %>
    A publishing system for government open data by <a href="http://www.ipublic.org/">iPublic.org</a>
    - Licensed under <a href="<%= url_for(:controller => '/public/welcome', :action => 'license') %>">MIT License</a>
  </p>
	</div>
</div>

app/views/shared/_footer_public.html.erb
<div id="footer">
  <p>
	    <span style="float: right">
	      Join the OpenMedia Community! <a href="<%= url_for(:action=>'new', :controller=>'public/sites', :host=>OM_DOMAIN) %>">Sign up</a>
	    </span>
    A publishing system for government open data by <a href="http://www.ipublic.org/">iPublic.org</a>
    - Licensed under <a href="<%= url_for(:controller => '/public/welcome', :action => 'license') %>">MIT License</a>
  </p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <% skip_nav ||= false %>
  <% unless skip_nav %>
  <%= render :partial => 'shared/nav_service' %>
  <% end %>
	
	<%#= image_tag "openmedia_logo.png", {:alt => "Civic OpenMedia"} %>
	<h1 id="branding"><%= link_to 'Civic OpenMedia Online', root_path %></h1>

	<!-- <div class="search">
		<%#= render :partial => 'admin/search_form' %>
	</div> -->
</div>
<div class="clear"></div>

app/views/shared/_map.html.erb
<% content_for :head do %>

	<!-- Use Dojo Claro 1.6 stylesheet (it interferes less with core CSS properties than ESRI-provded 1.5) -->
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/dojo/1.6/dijit/themes/claro/claro.css" %>
	<meta name="Viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">

	<%= javascript_include_tag "http://serverapi.arcgisonline.com/jsapi/arcgis/?v=2.2" %>
	<%= javascript_include_tag "map-arcgis.js" %>

	<script type="text/javascript">
		dojo.require("dijit.layout.ContentPane");
		dojo.require("esri.map");
		
		function Init() {
			new dijit.layout.ContentPane({region: "center", style: "height: 100%; width: 100%; margin: 0; padding: 0; overflow: hidden;"},"map");
//			var map = new esri.Map("map");
// Washington, DC
		var initExtent = new esri.geometry.Extent(
			{"xmin":-8591189.922223657,
			 "ymin":4695514.45486338,
			 "xmax":-8557557.629778225,
			 "ymax":4726089.266177409,
			 "spatialReference":{"wkid":102100}
			});
			map = new esri.Map("map",{extent:initExtent});

			var layer = new esri.layers.ArcGISTiledMapServiceLayer("http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer");
			map.addLayer(layer);
			var resizeTimer;
			dojo.connect(map, 'onLoad', function(theMap) {
				dojo.connect(dijit.byId('map'), 'resize', function() {
					clearTimeout(resizeTimer);
					resizeTimer = setTimeout( function() {
						map.resize();
						map.reposition();
					}, 500);
				});
			});
		}
		dojo.addOnLoad(Init);
	</script>
<% end %>

<div id="map">
</div>

app/views/shared/_nav_main.html.erb
<ul id="nav" class="tabs">
	<li id="home" class="active"><%= link_to 'Home', admin_root_path %>
	<li id="sources"><%= link_to 'Data Sources', admin_datasources_path, :title => "" %>
	<li id="collections"><%= link_to 'Collections', admin_linked_data_collections_path, :title => "" %>
	<li id="maps"><%= link_to 'Maps', admin_maps_path, :title => "" %>
	<li id="dashboards"><%= link_to 'Dashboards', admin_dashboards_path, :title => "" %>
	<li id="site"><%= link_to 'Site', admin_site_path, :title => "" %>	
	<li id="contacts"><%= link_to 'Contacts', admin_contacts_path, :title => "" %>
	<li id="help"><%= link_to 'Help', '/about', :title => "" %>
	<li id="support"><%= link_to 'Support', '/support', :title => "" %></li>
</ul>

app/views/shared/_nav_service.html.erb
<ul id="nav-service" class="nav-service">
	<% if !current_admin %>
	  <!--<li><= link_to "Register", new_user_registration_path ></li>-->
	  <li><%= link_to "Sign In", new_admin_session_path %></li>
	<% else %>
	  <li><%= link_to "Sign out", destroy_admin_session_path,
				:confirm => "Are you sure you want to sign out?" %></li>
	  <li><%= link_to current_admin.email, edit_admin_registration_path %></li>
	<% end %>	
</ul>

app/views/shared/_public_nav_main.html.erb
<ul class="nav main">
	<li><%= link_to 'Home', public_collections_path, :title => "" %>
	<li><%= link_to 'Map', public_maps_path, :title => "" %>
	<li class="secondary">
		<%= link_to 'Support', '/support', :title => "" %>
	</li>
</ul>					