config/routes.rb
Openmedia::Application.routes.draw do

  devise_for :admins

  match '/admin' => 'admin/home#index', :as => :admin_root
  match '/about' => 'admin/home#about', :as => :about
  match '/support' => 'admin/home#support', :as => :support

  root :to => "public/welcome#index"
  
  scope :module => 'public' do
    resources :sites do
      collection do
        get :autocomplete_geoname
      end
    end
    resources :collections
    resources :classes
    resources :maps
    resources :dashboards
    resources :welcome do
      collection do
        get :license
      end
    end
  end
  
  namespace :admin do
    resources :csvs do
      collection do
        get :import
        post :upload
      end
    end
    resource :site
    resource :community
    resources :contacts do
      collection do
        get :new_email
        get :new_telephone
        get :new_address
      end
      member do
        get :show_contact
      end
    end
    resources :dashboards do
      collection do
        get :new_group
        get :new_measure
      end
    end
    resources :maps
    
    namespace :linked_data do
      resources :collections do
        resources :vocabularies do
          resources :types
          resources :properties
        end
      end
    end

    namespace :schema do
      resources :collections do
        resources :classes
      end
      resources :classes do
        collection do
          get :new_property
          get :autocomplete
          get :property_list
        end
      end
    end    
    
    resources :datasources do
      collection do
        get :new_property
      end

      member do
        get :raw_records
        get :publishing
        put :publish
      end
    end
    
    resources :catalogs
    resources :properties
    resources :settings
    resources :reports
    resources :vcards
    resources :schedules
    resources :data_types
  end

end

app/models/linked_data/data_source.rb
class LinkedData::DataSource < CouchRest::Model::Base

  attr_accessor :docs_read, :docs_written
  
  use_database STAGING_DATABASE
  unique_id :identifier
  
  CSV_SOURCE_TYPE = "csv"
  SHAPEFILE_SOURCE_TYPE = "shapefile"
  URL_SOURCE_TYPE = "url"
  
  property :term, String
  property :identifier, String
  property :label, String
  property :properties, [LinkedData::Property]

  # property :transform_model do
  #   property :exe_order, Float
  #   property :source_property_term, String
  #   property :destination_topic_id, String
  #   property :destination_topic_property_term, String
  #   property :method, String
  #   property :parameters, String
  # end
  
  property :extract_sets do
    property :serial_number, String
    property :docs_written, Integer
    property :extracted_at, Time
  end

  timestamps!

  validates_presence_of :term
  
  ## Callbacks
  before_create :generate_identifier

  design do
    view :by_term
    view :by_label
  end
  
  def last_extract(view_opts={})
    unless self.extract_sets.nil?
      LinkedData::RawRecord.by_serial_number({:key=>self.extract_sets.last.serial_number}.merge(view_opts))
    end
  end

  def raw_records(view_opts={})
    LinkedData::RawRecord.by_data_source_id({:key=>self.id}.merge(view_opts))
  end  

  def unpublished_raw_records(view_opts={})
    LinkedData::RawRecord.by_unpublished({:key=>self.id}.merge(view_opts))
  end  
  
  def raw_doc_count
    LinkedData::RawRecord.by_data_source_id(:key=>self.id, :include_docs=>false)['rows'].size
  end

  def raw_doc_published_count(view_opts={})
    LinkedData::RawRecord.by_data_source_id_and_published(:startkey=>[self.id], :endkey=>[self.id, {}], :include_docs=>false)['rows'].size
  end
  
  def self.serial_number
    ::Digest::MD5.hexdigest(Time.now.to_i.to_s + rand.to_s).to_s
  end
  
  def extract!(records)
    raise "DataSource must be saved to database first" if self.identifier.nil?
    esn = LinkedData::DataSource.serial_number
    ts = Time.now.utc
    extract_prop_set = {:serial_number => esn, :data_source_id => self.identifier, 
                        :created_at => ts, :updated_at => ts}
    
    records.each do |rec|
      LinkedData::RawRecord.database.bulk_save_doc(rec.merge(extract_prop_set))
      self.docs_written += 1
      LinkedData::RawRecord.database.bulk_save if docs_written%500 == 0              
    end
    LinkedData::RawRecord.database.bulk_save
    extract_sets << Hash[:serial_number => esn, :docs_written => docs_written, :extracted_at => ts]
    self.save # Persist the updated extract_sets array 
    extract_sets.last
  end
  
  
  def transform!
    # generate ctl from dataset and source definition
    ctl = "source :in, {:datasource=>'#{self.id}'}, #{instance_properties}\n"
    ctl << "destination :out,{:order=> #{instance_properties}}\n"

    
    # ctl = "source :in, {:datasource=>'#{self.id}'}, ["+
    #   self.source_properties.collect{|p| p.identifier}.collect{|p| ":#{p}"}.join(',') + "]\n"
    # ctl << "destination :out, {:rdfs_class=>'#{self.rdfs_class_uri}'}, {:order=>[" +
    #   self.rdfs_class.properties.collect{|p| p.identifier}.collect{|p| ":#{p}"}.join(',') + "]}\n"

    ETL::Engine.init(:datasource=>self)
    ETL::Engine.process_string(self, ctl)
    ETL::Engine.import = nil
    metadata.update!(:modified=>DateTime.now)
    ETL::Engine.rows_written
  end
  
  def docs_read
    @docs_read ||= 0
  end
  
  def docs_written
    @docs_written ||= 0
  end
  

private
  def generate_identifier
    self.label ||= self.term
    self['identifier'] = self.class.to_s.split("::").last.downcase + '_' +
                         escape_string(self.term.downcase) if new?
  end

  def escape_string(str)
    str.gsub(/[^A-Za-z0-9]/,'_').squeeze('_')
  end
  
end

app/controllers/admin/datasources_controller.rb
# require 'csv'
require_dependency 'csv'
require 'tmpdir'

class Admin::DatasourcesController < Admin::BaseController

  skip_before_filter :verify_authenticity_token, :only => [:create]

  def index
    @datasources = current_site.datasources
  end

  def new
    @datasource = OpenMedia::Datasource.new(:column_separator=>',', :skip_lines=>0)
  end  
  
  def show
    @datasource = OpenMedia::Datasource.get(params[:id])
    @documents = []
    if @datasource.rdfs_class
      model = @datasource.rdfs_class.spira_resource
      model.default_source(@datasource.rdfs_class.skos_concept.collection.repository)
    end
  end
  
  def create
    @datasource = OpenMedia::Datasource.new(params[:datasource])
    
    if @datasource.save
      logger.debug("saved #{@datasource.id}")
      # this was here for Refine, commenting out for datasource workflow changes
      #if data_file
      #  data_file = data_file.respond_to?(:tempfile) ? data_file.tempfile : data_file
      #  @datasource.import_data_file!(data_file, :has_header_row=>has_header_row, :delimiter_character=>delimiter_character)
      #end
      current_site.datasources << @datasource
      current_site.save!
      
      if @datasource.textfile_source? && params[:textfile]
        @datasource.initial_import!(params[:textfile])
      elsif @datasource.shapefile_source? && params[:shapefile] && params[:shapefile].content_type =~ /(zip|ZIP)$/
        @datasource.initial_import!(params[:shapefile])
      elsif @datasource.webservice_source?
        @datasource.initial_import!
      end

      respond_to do |format|
        format.html do
          flash[:notice] = 'Datasource successfully created.'
          redirect_to admin_datasource_path(@datasource)
        end

        format.json { render :json=>{id=>@datasource.identifier}, :status=>:created }
      end

    else
      respond_to do |format|
        format.html do
          flash[:error] = 'Unable to create Datasource.'
          render :action => "new"
        end

        format.json do
          render :text=>@datasource.errors.full_messages*"\n", :status=>400
        end
      end
    end
  end

  def raw_records
    @datasource = OpenMedia::Datasource.find(params[:id])
    count = @datasource.raw_record_count
    records = @datasource.raw_records(:limit=>params[:iDisplayLength], :skip=>params[:iDisplayStart])
    render :json=>{
      :sEcho=>params[:sEcho],
      :aaData=>records.collect{|rr| @datasource.source_properties.collect{|p| rr[p.identifier]}},
      :iTotalRecords=>count,
      :iTotalDisplayRecords=>count
    }
  end

     
  def edit
    @datasource = OpenMedia::Datasource.get(params[:id])
    # @vcards = OpenMedia::Schema::OWL::Class.for(RDF::VCARD.VCard).spira_resource.each.to_a
    if @datasource.nil?
      flash[:error] = 'Datasource not found.'
      redirect_to(admin_datasources_url)
    end
  end
  
  def update
    @datasource = OpenMedia::Datasource.get(params[:id])
    @datasource.update_attributes_without_saving(params[:datasource])
    # @datasource.metadata.update_attributes_without_saving(params[:datasource])

    respond_to do |format|    
      if @datasource.save!
        flash[:notice] = 'Successfully updated Datasource.'
        format.html { redirect_to(admin_datasources_path) }
        format.xml  { head :ok }    
      else
        format.html do
          # @vcards = OpenMedia::Schema::OWL::Class.for(RDF::VCARD.VCard).spira_resource.each.to_a
          render :action => "edit"
        end
        format.xml  { render :xml => @datasource.errors, :status => :unprocessable_entity }
      end
    end      
  end

  def new_property
    @property = OpenMedia::DatasourceProperty.new
    render :partial=>'datasource_property', :locals=>{ :property=>@property }
  end

  def publishing
    @datasource = OpenMedia::Datasource.get(params[:id])
    @collections = om_site.skos_collection.sub_collections.sort{|c1,c2| c1.label <=> c2.label}
    @collections.concat(current_site.skos_collection.sub_collections.sort{|c1,c2| c1.label <=> c2.label}) unless current_site = om_site        
  end

  def publish
    @datasource = OpenMedia::Datasource.get(params[:id])
    params[:datasource].delete(:source_properties)  # just discard transformation data for now
    @datasource.update_attributes_without_saving(params[:datasource])    

    # create rdfs class with same properties/typea as datasource
    @collection = OpenMedia::Schema::SKOS::Collection.for(params[:collection_uri])
    if @datasource.rdfs_class_uri.blank? && @collection.exists?
      @class = OpenMedia::Schema::RDFS::Class.create_in_site!(current_site, :label=>@datasource.title, :comment=>params[:datasource][:metadata][:description])
      @collection.members << @class.uri
      @collection.save!
      @datasource.source_properties.each_with_index do |prop,idx|
        @class.properties << OpenMedia::Schema::RDF::Property.create_in_class!(@class, :label=>prop.label, :range=>RDF::URI.new(prop.range_uri))
      end
      @class.save!          
      @datasource.rdfs_class_uri = @class.uri.to_s
    end    

    @datasource.update_metadata(params[:datasource][:metadata])    
    @datasource.save!
    @datasource.publish!
    flash[:notice] = 'Dataset Published Successfully'
    redirect_to admin_datasource_path(@datasource)
  end


  def destroy
    @datasource = OpenMedia::Datasource.get(params[:id])
    
    unless @datasource.nil?
      @datasource.destroy
      redirect_to(admin_datasources_path)
    else
      flash[:error] = "The Datasource could not be found, refresh the catalog list and try again."
      redirect_to(admin_datasources_path)
    end
  end

  def upload
    # either create new datasource and save seed data or do import on existing datasource
    textfile = params.delete(:textfile)
    shapefile = params.delete(:shapefile)
    datafile = textfile || shapefile    
    seed_data_attachment = nil
    if params[:datasource_id]
      @datasource = OpenMedia::Datasource.get(params[:datasource_id])
      count = @datasource.import!(:file=>(datafile.respond_to?(:tempfile) ? datafile.tempfile.path : datafile.path))
      flash[:notice] = "Imported #{count} records into datasource #{@datasource.title}"      
      redirect_to admin_datasources_path
    elsif params[:datasource]      
      @datasource = OpenMedia::Datasource.new(params[:datasource])
      properties = []
      if @datasource.textfile_source? && textfile
        # parse first line of file and setup properties
        has_header_row = params.delete(:has_header_row)
        data = CSV.parse(textfile.read, {:col_sep=>@datasource.column_separator})
        if has_header_row
          @datasource.skip_lines = 1
          properties = data[0].collect{|pn| {:label=>pn, :range=>RDF::XSD.string}}
        else
          1.upto(data[0].size) {|i| properties << {:label=>"Column#{i}", :range=>RDF::XSD.string}}
        end
        textfile.rewind        
        @datasource.create_attachment(:file=>(textfile.respond_to?(:tempfile) ? textfile.tempfile : textfile), :name=>'seed_data',
                                        :content_type=>textfile.content_type)            
        
      elsif @datasource.shapefile_source? && shapefile
        if shapefile.content_type =~ /(zip|ZIP)$/
          Dir.mktmpdir do |temp_dir|
            `#{UNZIP} #{shapefile.path} -d #{temp_dir}`
            shpfn = Dir.glob(File.join(temp_dir,'*.shp')).first
            if shpfn
              jsfn = shpfn.gsub(/\.shp/,'.js')
              %x!#{OGR2OGR} -t_srs EPSG:4326 -a_srs EPSG:4326 -f "GeoJSON" #{jsfn} #{shpfn}!
              File.open(jsfn) do |jsf|
                geojson = JSON.load(jsf)
                properties = geojson['features'].first['properties'].collect do |k,v|
                  range = case v
                            when TrueClass, FalseClass then RDF::XSD.boolean
                            when Fixnum then RDF::XSD.integer
                            when Float then RDF::XSD.float
                            else RDF::XSD.string
                          end
                  {:label=>k, :range=>range}
                end
                properties << {:label=>'geometry', :range=>RDF::OM_CORE.GeoJson}
                jsf.rewind
                @datasource.create_attachment(:file=>jsf, :name=>'seed_data',
                                              :content_type=>'application/json')            
                
              end              
            else
              @datasource.errors.add(:shapefile, "No .shp file found inside zip")
            end

          end
        else
          @datasource.errors.add(:shapefile, "Please select a zip file")
        end
      else
        @datasource.errors.add(:base, "Please select a file")
      end

      if @datasource.errors.size == 0 &&@datasource.rdfs_class_uri.blank?
        @collection = OpenMedia::Schema::SKOS::Collection.for(params[:collection_uri])
        if @collection.exists?
          @class = OpenMedia::Schema::RDFS::Class.create_in_site!(current_site, :label=>@datasource.title)
          @collection.members << @class.uri
          @collection.save!
          properties.each_with_index do |prop,idx|
            prop[:label] = "Column#{idx+1}" if prop[:label].nil?
            prop[:label] = "#{@class.label} #{prop[:label]}" if prop[:label].downcase=='type'
            prop[:label] = "Col #{prop[:label]}" if prop[:label] =~ /^\d*$/              
            @class.properties << OpenMedia::Schema::RDF::Property.create_in_class!(@class, :label=>prop[:label], :range=>prop[:range])
            @datasource.source_properties << OpenMedia::DatasourceProperty.new(:label=>prop[:label], :range_uri=>RDF::XSD.string.to_s)
          end
          @class.save!          
          @datasource.rdfs_class_uri = @class.uri.to_s
          
        else
          @datasource.errors.add(:base, "Please select an existing Class or choose a Collection to create new Class in")
        end
      end

app/views/admin/datasources/_datasource_property.html.erb
<li class="datasource-property">
  <ol>
    <li>
      <label class="narrow">Name</label>
      <input name="datasource[source_properties][][label]" class="standard" type="text" value="<%= property.label %>"/>
    </li>
    <li>
      <%= label_tag "datasource[source_properties][]#{property.label}_range_name", 'Type', :class => "narrow" %>
      <%= text_field_tag "datasource[source_properties][]#{property.label}_range_name", short_uri(property.range_uri),
	  :class=>'property-range-uri' %>
      <input type="hidden" name="datasource[source_properties][][range_uri]" value="<%= property.range.to_s %>"/>
    </li>
    <li>
      <%= label_tag "datasource[source_properties][]#{property.label}_comment", 'Description', :class => "narrow" %>
      <textarea name="datasource[source_properties][][comment]" rows="2" class="standard"><%= property.comment %></textarea>
		</li>
		<li>
			<a href="#" class="delete-datasource-property delete-element" alt="Delete">Delete Property</a>
    </li>
  </ol>
</li>

app/views/admin/datasources/edit.html.erb
<% title "Data Sources > Edit: #{@datasource.title}" %>
<div class="grid_12">
  <p class="page-nav">
    <%#= link_to 'Refine Content', refine_admin_datasource_path(@datasource) %> 
    <%#= link_to 'Describe Datasource', describe_admin_datasource_path(@datasource) %>

    <%= link_to 'All Datasources', admin_datasources_path %> | 
    <%= link_to "Show", admin_datasource_path(@datasource) %> 
    <%#= link_to 'Publish', publishing_admin_datasource_path(@datasource) %> 
    <%#= link_to 'Delete', admin_datasource_path(@datasource), :confirm => 'Are you sure?', :method => :delete %>
  </p>
<hr/>
  <%= form_for :datasource, :url=>admin_datasource_path(:id=>@datasource.id), :html=>{:method=>:put} do |ds| %>
  <div class="box">
    <%= render :partial=>'form', :locals=>{:ds=>ds} %>
  </div>
	<fieldset class="omega submit">
	  <ol>
	    <li><%= ds.submit "Save", :class => "submit"%> <%= link_to 'Back', :back %></li>
	  </ol>
	</fieldset>
  <% end %>
</div>

app/views/admin/datasources/index.html.erb
<% title "Data Sources" %>
<div class="grid_12">
	<p><%= link_to 'Add Data Source', new_admin_datasource_path %></p>
	<hr/>
</div>
<div class="grid_8">
	<div class="block" id="tables">
	  <table>
			<thead>
			  <tr>
			    <th>Title</th>
			    <th>Source Type</th>
			    <th>Parser</th>
			    <th>Class</th>
			    <th>Updated</th>
			  </tr>
			</thead>
			<% @datasources.each do |ds| %>
				<tr>
				  <td><%= link_to ds.title, admin_datasource_path(ds.id) %></td>
				  <td><%= ds.source_type.titleize %></td>
				  <td><%= ds.parser.titleize %></td>
				  <td>
				    <% if ds.rdfs_class && ds.rdfs_class.exists? %>
				    <%= link_to ds.rdfs_class.label, admin_schema_collection_class_path(rdf_id(ds.rdfs_class.skos_concept.collection), rdf_id(ds.rdfs_class)) %>
				    <% end %>
				  </td>
				  <td><%= ds.updated_at.to_s(:full) %></td>
				</tr>
			<% end %>
	  </table>
	</div>
</div>

<div class="grid_4">
	<div class="box articles">
		<div class="block" id="articles">
			<div class="first article">
				<h3>Content Sources</h3>
				<p class="meta">Upload and publish data sets</p>
			</div>
		</div>
	</div>
</div>

app/views/admin/datasources/new_import.html.erb
<% title "New Dataset" %>
<div class="grid_4">
	<div class="box">
		<h2>Steps</h2>
		<div class="block">
			<ol>
				<li>Define Dataset</li>
				<li>Upload content</li>
				<b><li>Import content</li></b>
			</ol>
		</div>
	</div>
	
	<div class="box">
		<h2>About</h2>
		<div class="block">
			<p>Review uploaded content.</p>  
			<p>Verify datasource properties and values are correct.  If not, click your web browser's Back button and change upload settings.</p>
			<ol>
				<li>Unique ID property: is one of the properties a unique key for this datasource?  If you don't specify a Unique ID, OpenMedia will generate one for you, but future record updates and linking between datasources may be more difficult.</li>
				<li>Previous|Next: use these links to browse records.</li>
				<li>Import: click button to create Staging database records for uploaded datasource values.</li>
			</ol>
		</div>
	</div>
	
	<div class="box">
		<h2>Tools</h2>
		<div class="block">
			<ul>
				<li>Add Property</li>
				<li>Identify Address properties</li>
				<li>Identify Coordinate properties</li>
				<li>Import content</li>
			</ul>
		</div>
	</div>
	
</div>
<div class="grid_8">
	<div class="box">
		<h2>Uploaded Content</h2>
		<div class="block">
			<div class="box">
				<h5>Datasource title: <%= @datasource.title %></h5>
				<%= form_for :datasource, :url => import_admin_datasource_path(@datasource.identifier), :html=>{:method=>:put} do |f| %>
				  <p><%= f.label :unique_id_property, "Unique ID property:" %><b/> 
				    <%= f.select(:unique_id_property, @property_options, {:prompt => '-OpenMedia Generated-'}) %>
				  </p>
				  <%= render :partial => 'record', :object=>@record %>
				  <p><%= submit_tag 'Import' %></p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/admin/datasources/preview.html.erb
<% title "Preview Dataset" %>
<div class="grid_12" >
	<p style="float:right;">
		<%= link_to 'New Dataset', new_admin_datasource_path %>
	</p>
	<hr/>
</div>
<div class="grid_12">
	<p>The table below shows the first 10 uploaded records. Click 'Import' if you wish to add the uploaded content to the database.</p>
	<div class="box">
		<h2>Uploaded Content</h2>
		<div class="block" id="tables">
			<table>
				<thead>
				<tr>
					<% @xtab.column_names.each do |col| %>
						<th><%= col %></th>
					<% end %>
				</tr>
				</thead>
				<% unless @xtab.data.nil? %>
					<% @xtab.data.each do |row| %>
					  <tr>
							<% row.attributes.each do |item| %>
								<td><%= row.get(item) %></td>
							<% end %>
					  </tr>
					<% end %>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/admin/datasources/publishing.html.erb
<% title "Data Source: " + @datasource.title  %>
<div class="grid_12">
  <p class="page-nav">
    <%= link_to 'All Datasources', admin_datasources_path %> | 
    <%= link_to "Edit", edit_admin_datasource_path(@datasource) %> |
    <%= link_to 'Delete', admin_datasource_path(@datasource), :confirm => 'Are you sure?', :method => :delete %>
  </p>
  <hr/>
  
  <h2>Publishing</h2>
  <%= form_for :datasource, :url=>publish_admin_datasource_path(:id=>@datasource.id), :html=>{:method=>:put} do |ds| %>
  <%= ds.error_messages %>
  <div class="box">
    <fieldset>
      <legend>Summary</legend>
      <ol>
	<li>Published Records: <%= @datasource.published_raw_record_count %><br/>
	    Unpublished Records: <%= @datasource.raw_record_count - @datasource.published_raw_record_count %>
	</li>
      </ol>
    </fieldset
  <div class="box">
    <fieldset>
      <legend>Metadata</legend>
      <ol>
	<%= ds.fields_for :metadata, @datasource.metadata do |m| %>
	<li><%= m.label :description, :class => 'narrow' %> <%= m.text_area :description, :rows => 3, :class => 'wide' %></li>
	<% end %>

	<li>
	  <label for="datasource-creator" class="narrow">Creator</label> 
		<%= ds.select :creator_contact_id, contacts_collection, {:prompt => 'Select Contact', :include_blank => true}, :class => "wide" %>
	</li>

	<li>
	  <label for="datasource-publisher" class="narrow">Publisher</label> 
		<%= ds.select :publisher_contact_id, contacts_collection, {:prompt => 'Select Contact', :include_blank => true}, :class => "wide" %>
	</li>
      </ol>
    </fieldset>
    
    <fieldset>
      <legend>Schema</legend>
      <ol>

	<!--<li>
	  <%#= ds.label :rdfs_class_uri, 'Class', :class => 'narrow' %>
	  <input class="datasource-class-uri wide" name="rdfs-class-identifier" type="text" value="<%#= @datasource.rdfs_class.uri.path.split('/').last if @datasource.rdfs_class %>"/>
	  <%= ds.hidden_field :rdfs_class_uri %>
	</li>-->

	<!--<li>OR create new class in collection:</li>-->
	<li>
	  <p>Choose the collection to place the new schema class:</p>
	  <label class='narrow'>Collection</label> 
	  <select name="collection_uri">
	    <%= options_for_select @collections.collect {|c| [c.label, c.uri]} %>
	  </select>
	</li>
      </ol>
    </fieldset>

    <fieldset>
      <legend>Data Transformation</legend>

      <table style="width: 800px">
	<thead>
	  <tr>
	    <th colspan="2">Source</th><th colspan="2">Destination</th>
	  </tr>
	  <tr>
	    <th>Property Name</th><th>Type</th><th>Property Name</th><th>Type</th>
	  </tr>
	</thead>
	<% @datasource.source_properties.sort {|p1,p2| p1.label <=> p2.label}.each do |sp| %>	
	<tr>
	  <td><%= sp.label %></td>
	  <td><span class="tooltip" title="<%=sp.range_uri%>"><%= short_uri(sp.range_uri) %></span></td>
	  <td>	    
	    <%= render :partial=>'rdf_property_select', :locals=>{ :rdfs_class=>@datasource.rdfs_class, :selected=>sp.rdf_property_uri || sp.identifier } %>
	  </td>
	  <td><!-- short_uri(sp.rdf_property.range) -->
	    <%= short_uri(sp.range_uri) %>
	  </td>
	</tr>
	<% end %>
      </table>


    </fieldset>


  </div>

  <fieldset class="omega submit">
    <ol>
      <li><%= ds.submit "Publish", :class => "submit", :id=>'publish-button', :disabled=>true %> <%= link_to 'Back', :back %></li>
    </ol>
  </fieldset>
  <% end %>
</div>

app/views/admin/datasources/show.html.erb
<% title "Data Source > Publish: " + @datasource.title %>
<div class="grid_12">
	<p class="page-nav">
		<%#= link_to 'Refine Content', refine_admin_datasource_path(@datasource) %> 
		<%#= link_to 'Describe Datasource', describe_admin_datasource_path(@datasource) %>

		<%= link_to 'All Datasources', admin_datasources_path %> | 
		<%= link_to "Edit", edit_admin_datasource_path(@datasource) %> |
		<%= link_to 'Publish', publishing_admin_datasource_path(@datasource) %> |
		<%= link_to 'Delete', admin_datasource_path(@datasource), :confirm => 'Are you sure?', :method => :delete %>	</p>
	<hr/>

	<div class="box">
			<%= show_fields(@datasource, [:title, :uri, 
			    [:rdfs_class_uri, 'Type']]) %>
			<table class="property-table">
			  <tr>
			    <th class="property-table">Description:</th>
			    <td><%= @datasource.metadata.description if @datasource.metadata %>
			  </tr>

			  <tr>
			    <th class="property-table">Creator:</th>
			    <td><%#= vcard_label(@datasource.creator) %>
			  </tr>

			  <tr>
			    <th class="property-table">Publisher:</th>
			    <td><%#= vcard_label(@datasource.publisher) %>
			  </tr>
			</table>

			<%= show_fields(@datasource, [:source_type, :parser, [:column_separator, 'Separator'], 
			                              :has_header_row]) %>
		</div>
</div>

<div class="grid_12" style="overflow: auto">
  <div class="box">
    <h2>Unpublished Data</h2>
		<div class="block">

    <table id="raw-data-table" class="display">
      <thead>
	<tr>
	  <% @datasource.source_properties.each do |p| %>
	  <th><%= p.label %></th>
	  <% end %>
	</tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>
</div>

<script>
$(function() {
  $('#raw-data-table').dataTable({'sAjaxSource': '/admin/datasources/<%= @datasource.id %>/raw_records.json',
                                  'bFilter': false,
                                  'bSort': false,
                                  'bProcessing': true,
                                  'bScrollCollapse': true,
                                  'bServerSide': true,
                                  'sScrollX': '100%',
                                  'sPaginationType': 'full_numbers'});
});
</script>