config/routes.rb
Openmedia::Application.routes.draw do

  devise_for :admins

  match '/admin' => 'admin/home#index', :as => :admin_root
  match '/about' => 'admin/home#about', :as => :about
  match '/support' => 'admin/home#support', :as => :support

  root :to => "public/welcome#index"
  
  scope :module => 'public' do
    resources :sites do
      collection do
        get :autocomplete_geoname
      end
    end
    resources :collections
    resources :classes
    resources :maps
    resources :dashboards
    resources :welcome do
      collection do
        get :license
      end
    end
  end
  
  namespace :admin do
    resources :csvs do
      collection do
        get :import
        post :upload
      end
    end
    resource :site
    resource :community
    resources :contacts do
      collection do
        get :new_email
        get :new_telephone
        get :new_address
      end
      member do
        get :show_contact
      end
    end
    resources :dashboards do
      collection do
        get :new_group
        get :new_measure
      end
    end
    resources :maps
    
    namespace :linked_data do
      resources :collections do
        resources :vocabularies do
          resources :types
          resources :properties
        end
      end
    end

    namespace :schema do
      resources :collections do
        resources :classes
      end
      resources :classes do
        collection do
          get :new_property
          get :autocomplete
          get :property_list
        end
      end
    end    
    
    resources :datasources do
      collection do
        get :new_property
      end

      member do
        get :raw_records
        get :publishing
        put :publish
      end
    end
    
    resources :catalogs
    resources :properties
    resources :settings
    resources :reports
    resources :vcards
    resources :schedules
    resources :data_types
  end

end

app/models/open_media/dashboard.rb
class OpenMedia::Dashboard < CouchRest::Model::Base
  
  # use_database SITE_DATABASE
  use_database VOCABULARIES_DATABASE

  FORMATS = %w(percentage currency number string)
  VISUALS = %w(inlinesparkline pie inlinebar bullet)
  
  ## Property Definitions
  # General properties
  property :title
  property :description
  property :groups, [OpenMedia::DashboardGroup], :default => []
  
  timestamps!
  
  validates :title, :presence => true
  view_by :title

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  
  def index
    @dashboards = OpenMedia::Dashboard.all
  end
  
  def show
    @dashboard = OpenMedia::Dashboard.get(params[:id])
  end

  def new
    @dashboard = OpenMedia::Dashboard.new
    @dashboard_group = OpenMedia::DashboardGroup.new
  end

  def new_group
    render :partial=>'form_dashboard_group', :locals=> { :group=>OpenMedia::DashboardGroup.new }
  end

  def new_measure
    render :partial=>'form_measure', :locals=> { :measure=>OpenMedia::DashboardMeasure.new }
  end
  

  def create
    @dashboard = OpenMedia::Dashboard.new(params[:dashboard])

    if @dashboard.save
      flash[:notice] = 'Successfully created Dashboard.'
      redirect_to(admin_dashboard_path(@dashboard))
    else
      flash[:error] = 'Unable to create Dashboard.'
      render :action => "new"
    end
  end

  def edit
    @dashboard = OpenMedia::Dashboard.get(params[:id])
    @dashboard_groups = @dashboard.groups
  end
  
  def update
    @dashboard = OpenMedia::Dashboard.get(params[:id])
    @dashboard.attributes = params[:dashboard]
    @dashboard.groups = nil unless params[:dashboard][:groups]
    respond_to do |format|
      if @dashboard.save
        flash[:notice] = 'Successfully updated Dashboard.'
        format.html { redirect_to(admin_dashboard_path) }
        format.xml  { head :ok }
      else
        flash[:error] = "Error updating Dashboard."
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dashboard.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  
  # DELETE /dashboards/:id
  def destroy
    @dashboard = OpenMedia::Dashboard.get(params[:id])
    unless @dashboard.nil?
      @dashboard.destroy
      redirect_to(admin_dashboards_url)
    else
      flash[:error] = "The Dashboard could not be found, refresh the Dashboard list and try again."
      redirect_to(admin_dashboards_url)
    end
  end
  
end

app/views/admin/dashboards/_form.html.erb
<div class="grid_9">
  <div class="box">
      <%= f.error_messages %>
      <%= f.hidden_field :rev, :value => @dashboard['_rev'] if @dashboard['_rev'] %>
      <fieldset>
	<ol>
	  <li><%= f.label :title %> <%= f.text_field :title, :class => "wide" %></li>
	  <li><%= f.label :description, :style => "clear:left;"  %> <%= f.text_area :description, :rows => 3, :class => "wide" %></li>
	</ol>
      </fieldset>

      <fieldset class="omega">
	<legend>Measure Groups</legend>
	<% for group in @dashboard.groups {|p1,p2| p1.title <=> p2.title} %>
		<%= render :partial => 'form_dashboard_group', :locals => {:group => group} %>
	<% end %>
	<a href="#" class="add-measure-group add-element">Add Measure Group</a>
      </fieldset>
      
      <fieldset class="submit">
	<ol>
	  <li><%= f.submit "Save", {:class => "submit"} %> <%= link_to 'Back', :back %></li> 
	</ol>
      </fieldset>
  </div>
</div>

app/views/admin/dashboards/_form_dashboard_group.html.erb
<ol>
  <li>
    <label>Title</label>
    <input name="dashboard[groups][][title]" type="text" value="<%= group.title %>"/>
  </li>
  <li>
    <label>Description</label>
    <input name="dashboard[groups][][description]" class="standard" type="text" value="<%= group.description %>"/>
  </li>
  <li>
    <a href="#" class="delete-dashboard-group delete-element">Delete Group</a>
  </li>
</ol>
<ol>
  <fieldset class="omega">
    <legend>Measures</legend>
    <% for measure in group.measures %>
    	<%= render :partial=>'form_measure', :locals=>{:measure=>measure} %>
    <% end %>      
    <a href="#" class="add-measure add-element">Add Measure</a>
  </fieldset>
</ol>

app/views/admin/dashboards/_form_measure.html.erb
<table class="measure">
	<tr>
  <td>
    <label>Measure Label</label><br/>
    <input name="dashboard[groups][][measures][][measure]" class="standard" type="text" value="<%= measure['measure'] %>"/>
  </td>
  <td>
    <label class='wide'>Sort Property</label><br/>
    <input name="dashboard[groups][][measures][][sort_property]" class="standard dashboard-property" type="text" value="<%= measure.sort_property %>"/>
  </td>
<td>&nbsp;</tr>
</tr>
	<tr>
  <td>
    <label class='wide'>Source Class</label><br/>
    <input class="standard dashboard-source-class" type="text" value="<%= last_url_component(measure['source_class']) %>"/>
    <input name="dashboard[groups][][measures][][source_class]" type="hidden" value="<%= measure['source_class'] %>"/>
  </td>
  <td>
    <!-- Present a tdst of Properties from the selected Class above - filter to numeric types -->
    <label class='wide'>Source Property</label><br/>
    <input name="dashboard[groups][][measures][][source_property]" class="standard dashboard-property" type="text" value="<%= measure.source_property %>"/>
  </td>
	<td>&nbsp;</tr>

</tr>
<tr>
  <td>
    <label class='wide'>Format</label>  <br/>  
    <select name="dashboard[groups][][measures][][format]", class="standard">
      <%= options_for_select([''].concat(OpenMedia::Dashboard::FORMATS), measure['format']) %>
    </select>
  </td>
  <td>
    <label class='wide'>Graph Type</label><br/>
    <select name="dashboard[groups][][measures][][visual]", class="standard">
      <%= options_for_select([''].concat(OpenMedia::Dashboard::VISUALS), measure['visual']) %>
    </select>
  </td>
	<td>&nbsp;</tr>

</tr>
<tr>
  <td>
    <label class='wide'>Rank</label><br/>
    <input name="dashboard[groups][][measures][][rank]" class="standard" type="text" value="<%= measure['rank'] %>"/>
  </td>
  <td>
    <label class='wide'>Description</label><br/>
    <input name="dashboard[groups][][measures][][description]" class="standard" type="text" value="<%= measure['description'] %>"/>

  </td>
  <td style="vertical-align: bottom">
    <a href="#" class="delete-measure delete-element" alt="Delete">Delete Measure</a>
  </td>
</tr>
</table>

app/views/admin/dashboards/edit.html.erb
<% title "Edit Dashboard: #{@dashboard.title}" %>
<div id="forms">
  <%= form_for :dashboard, :url => admin_dashboard_path(@dashboard), :html => {:method=>:put} do |f| %>
  <%= render :partial => 'form', :locals=> {:f=>f} %>
  <% end %>
</div>

app/views/admin/dashboards/index.html.erb
<% title "Dashboards" %>
<div class="grid_12">
	<p>
    <%= link_to 'Add Dashboard', new_admin_dashboard_path %>
  </p>
	<hr />
</div>

<div class="grid_8">
  <div class="box">
    <div class="block" id="tables">
      <table style="width: 100%">
				<thead>
				  <tr>
				    <th>Title</th>
				    <th>Description</th>
				  </tr>
				</thead>
				<% @dashboards.each do |dash| %>
				<tr>
				  <td><%= link_to dash.title, admin_dashboard_path(dash) %></td>
				  <td><%= dash.description %></td>
				</tr>
				<% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/dashboards/new.html.erb
<% title "Add Dashboard" %>
<div id="forms">
  <%= form_for :dashboard, :url => admin_dashboards_path do |f| %>
  <%= render :partial => 'form', :locals=> {:f=>f} %>
  <% end %>
</div>

app/views/admin/dashboards/show.html.erb
<% title "Dashboard: #{@dashboard.title}" %>
<div class="grid_12">
	<p>
    <%= link_to 'All Dashboards', admin_dashboards_path %> |
    <%= link_to 'Edit', edit_admin_dashboard_path %> |
    <%= link_to 'Delete', new_admin_dashboard_path %>
  </p>
	<hr />
</div>

<div class="grid_8">
	<% @dashboard.groups.each do |g|  %>
		<%= render :partial => '/public/dashboards/dashboard_group', :locals  =>{ :group => g } %>
	<% end %>
</div>